path = "/home/mbana/.espressif"
idf_path = "/home/mbana/.espressif/v6.1/esp-idf"
esp_idf_json_path = "/home/mbana/.espressif/tools"
tool_download_folder_name = "/home/mbana/.espressif/dist"
tool_install_folder_name = "/home/mbana/.espressif/tools"
target = ["all"]
idf_versions = ["v6.1"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://github.com"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = false
skip_prerequisites_check = false
cleanup = false
skip_components_download = false
python_env_folder_name = "python"
use_local_archive = "/home/mbana/.local/share/eim/offline_archives/archive_v6.1_linux-x64.zst"
activation_script_path_override = "/home/mbana/.espressif/tools"
python_version_override = "python313"
create_bat_activation_script = false
