# For all available options, see the probe-rs default configuration:
# https://github.com/probe-rs/probe-rs/blob/master/probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
[default.probe]
# protocol = "Jtag"
# protocol = "UART"
# USB vendor ID
usb_vid = "1a86"
# USB product ID
usb_pid = "55d3"
# Serial number
serial = "5B14108371"
# The protocol to be used for communicating with the target.
# If unset, the probe decides.
protocol = "Swd"
# The speed in kHz of the data link to the target.
# speed = 1337
# /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B14108371-if00

[default.general]
chip = "esp32s3"

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, format = "Defmt" },
]
tabs = [
    { up_channel = 0, name = "Logs" },
]
