[package]
edition = "2024"
name = "usb_otg-rs"
rust-version = "1.95"
version = "0.1.0"

[[bin]]
name = "usb_otg-rs"
path = "./src/bin/main.rs"
target = "xtensa-esp32s3-none-elf"

[dependencies]
embassy-executor = "0.10.0"
embassy-usb-host = { version = "0.1.0", features = ["log"] }
esp-backtrace = { version = "0.17.0", features = [
    "panic-handler",
    "println",
    "esp32s3",
] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3", "log-04"] }
esp-hal = { version = "1.0.0", features = [
    "esp32s3",
    "log-04",
    "unstable",
    "__usb_otg",
] }
esp-rtos = { version = "0.4.0", features = ["esp32s3", "log-04", "embassy"] }
esp-println = { version = "0.15.0", features = ["esp32s3", "log-04"] }
log = "0.4"
esp-sync = { version = "0.1.1", features = ["esp32s3", "log-04"] }
embassy-futures = "0.1.2"
embassy-usb = "0.6.0"
static_cell = "2.1.1"
embassy-sync = "0.8.0"
heapless = "0.9.3"
embassy-usb-driver = "0.2.2"
embassy-usb-synopsys-otg = "0.4.0"

[features]
esp32s3 = [
    "esp-backtrace/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-rtos/esp32s3",
    "esp-println/esp32s3",
    "esp-sync/esp32s3",
    "esp-hal/esp32s3"
]

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1
